# https://cwiki.apache.org/confluence/display/INFRA/.asf.yaml+features+for+git+repositories

github:
  description: "Asynchronously writes journal and snapshot entries to configured R2DBC databases so that Apache Pekko Actors can recover state"
  homepage: https://pekko.apache.org/
  labels:
    - pekko
    - pekko-persistence
    - r2dbc
    - journal
  
  features:
    # Enable wiki for documentation
    wiki: false
    # Enable issue management
    issues: true
    # Enable projects for project management boards
    projects: false

  enabled_merge_buttons:
    squash:  true
    merge:   false
    rebase:  true

  protected_branches:
    main: { }

notifications:
  commits:              commits@pekko.apache.org
  issues:               notifications@pekko.apache.org
  pullrequests:         notifications@pekko.apache.org
  discussions:          notifications@pekko.apache.org
